version: "3.7"
services:
  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./scripts/postgres/pg-init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./data/pg:/var/lib/postgresql/data
    ports:
      - "5433:5432"