#!/bin/bash
set -e
PGPASSWORD=$POSTGRES_PASSWORD
echo "*** CREATING DATABASE ***"
echo $DB_USER $DB_PSW $DB_NAME
psql -U $POSTGRES_USER <<EOSQL
CREATE USER "$DB_USER" WITH ENCRYPTED PASSWORD '$DB_PSW';
CREATE DATABASE "$DB_NAME";
GRANT ALL PRIVILEGES ON DATABASE "$DB_NAME" TO "$DB_USER";
EOSQL
echo "*** DATABASE CREATED! ***"
